version: '3'

services:
  eagle_db:
    build: ./db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ork
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d/
    container_name: eagle_db
    restart: always
    ports:
      - "5432:5432"
  eagle_redis:
    image: redis:latest
    volumes:
      - ./redis/data:/data:rw
    container_name: eagle_redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:rw
      - ./redis/data:/data:rw
    command:
      /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf "
  eagle_web:
    build: .
    restart: always
    volumes:
      - ./:/code
    ports:
      - "9000:9000"
    links:
      - eagle_db
      - eagle_redis
    depends_on:
      - eagle_db
      - eagle_redis
    container_name: eagle_web
  eagle_celery:
    build: .
    command: "celery -A celery_worker worker -l info -E -c 10 -Q eagle"
    user: nobody
    links:
      - eagle_db
      - eagle_redis
    depends_on:
      - eagle_db
      - eagle_redis
    volumes:
      - .:/code:ro
    container_name: eagle_celery
  eagle_beat:
    build: .
    command: "celery -A celery_worker beat -l info"
    links:
      - eagle_db
      - eagle_redis
    depends_on:
      - eagle_db
      - eagle_redis
    volumes:
      - .:/code:rw
    container_name: eagle_beat
  eagle_flower:
    build: .
    command: "celery -A celery_worker flower --address=0.0.0.0 --port=5555 --basic_auth=ddong:dong159357"
    user: nobody
    links:
      - eagle_db
      - eagle_redis
      - eagle_celery
    depends_on:
      - eagle_db
      - eagle_redis
      - eagle_celery
    volumes:
      - .:/code:ro
    ports:
      - "5555:5555"
    container_name: eagle_flower