version: '3'

services:
  db2:
    build: ./db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ork
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d/
    container_name: db2
    restart: always
    ports:
      - "5432:5432"
  web2:
    build: .
    restart: always
    volumes:
      - ./:/code
    ports:
      - "9000:9000"
    links:
      - db2
    depends_on:
      - db2
    container_name: web2
