version: '3'

services:
  eagle_db:
    build: ./db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ork
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d/
    container_name: eagle_db
    restart: always
    ports:
      - "5432:5432"
  eagle_redis:
    image: "redis:alpine"
    container_name: eagle_redis
    restart: always
    ports:
      - "6379:6379"
  eagle_web:
    build: .
    restart: always
    volumes:
      - ./:/code
    ports:
      - "9000:9000"
      - "5555:5555"
    links:
      - eagle_db
      - eagle_redis
    depends_on:
      - eagle_db
      - eagle_redis
    container_name: eagle_web
